apiVersion: v1
kind: Service
metadata:
  name: ping-pong-player
  labels:
    type: ping-pong-player
spec:
  selector:
    type: ping-pong-player
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3456
    nodePort: 32001
  type: NodePort
